# Generated by Django 4.0.2 on 2022-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='razorpay', max_length=100, null=True),
        ),
    ]
