# Generated by Django 4.0.2 on 2022-03-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0002_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='razorpay', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='referral_code',
            field=models.CharField(default='waves', max_length=50, null=True),
        ),
    ]
