# Generated by Django 4.0.2 on 2022-03-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('social_link_1', models.CharField(blank=True, max_length=500)),
                ('social_link_2', models.CharField(blank=True, max_length=500)),
                ('social_link_3', models.CharField(blank=True, max_length=500)),
                ('photo', models.ImageField(upload_to='photos/team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
