# Generated by Django 4.0.2 on 2022-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='waves_id',
            field=models.CharField(default=62773, max_length=200),
        ),
    ]
