# Generated by Django 4.0.2 on 2022-03-28 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('waves_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registeritem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waves_events.event'),
        ),
        migrations.AddField(
            model_name='registeritem',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.register'),
        ),
        migrations.AddField(
            model_name='registeritem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
